source 'https://rubygems.org'
#source 'http://gems.github.com'

gem 'rails', '3.2.1'
gem 'recurly', '~> 2.0.10'
gem 'gattica', :git => 'git://github.com/chrisle/gattica.git'
gem 'google-adwords-api'
gem 'google-dfp-api'
gem 'google-api-client'
gem 'oauth2'

gem 'json'
gem 'typhoeus', '0.4.2'
gem 'httparty'
gem 'nokogiri' 

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'


group :production do
  gem 'pg' 
  gem 'thin'
end
group :development, :test do
  gem 'sqlite3'
#  gem 'thin' 
  gem 'pry' 
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer'

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'date_validator'  

gem "omniauth"
gem 'omniauth-openid'
gem 'omniauth-google-apps'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
